### ISSUE TITLE
Assets available on Earth Engine

### ISSUE THREAD

**Issue by jessjaco** [Martin-Jung/Habitatmapping#2]
Are the image products available as assets for use on Google Earth Engine?

Do images of individual habitat classes exist?

**Comment by Martin-Jung** [comment]
The composite image and fractional cover estimates (per class) are available yes (send me a mail with your account name).
Note however that it is not guarenteed that I can host the versions for unlimited time (since asset space is limited).
Therefore safest approach is to download and upload the image yourself
https://zenodo.org/record/3925749

PS: 
Note that soon I will push an update that adds many marine classes and furthermore annual changemasks for the years 2016,2017,2018 and 2019. So stay tuned.

**Comment by jessjaco** [comment]
I uploaded my own asset since I only needed 1 country anyway. I will keep my eyes open for updates!
Thanks!
